---
title: "CEREGE Calibration Curve #1"
subtitle: "Canberra Inspector 1000 - NaI"
author: "CEREGE Luminescence Team"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amssymb}
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{CEREGE#1}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  fig.width = 7,
  fig.height = 5,
  comment = "#>"
)
```

```{r packages}
library(gamma)
library(magrittr)
```

## Import Files
```{r import}
# Import CNF files for calibration
# Skip the first chanels
calib_dir <- system.file("extdata/AIX100/calibration", package = "gamma")
(calib_spc <- read(calib_dir))

# Import CNF files for background noise measurement
# Skip the first chanels
noise_dir <- system.file("extdata/AIX100/background", package = "gamma")
(noise_spc <- read(noise_dir))
```

## Energy Scale Calibration
### Reference Spectra
Lines used for energy scale calibration (in keV):

* Pb212: 238 (85)
* K40: 1461 (495)
* Tl208: 2615 (870)

#### BRIQUE
```{r calibrate-BRIQUE}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["BRIQUE"]] %>%
  slice_signal(-1:-40) %>%
  stabilize_signal(sqrt) %>%
  smooth_signal(method = "savitzky", m = 21) %>%
  remove_baseline() %>%
  find_peaks()
# Set energy values
set_energy(pks) <- c(238, NA, NA, NA, 1461, NA, NA, 2615)
# Recalibrate the energy scale
BRIQUE <- calibrate_energy(calib_spc[["BRIQUE"]], pks)
```

```{r plot-BRIQUE, echo=FALSE}
plot(BRIQUE, pks) +
  ggplot2::theme_bw()
```

#### C341
```{r calibrate-C341}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["C341"]] %>%
  slice_signal(-1:-40) %>%
  stabilize_signal(sqrt) %>%
  smooth_signal(method = "savitzky", m = 21) %>%
  remove_baseline() %>%
  find_peaks()
# Set energy values
set_energy(pks) <- c(238, NA, NA, NA, 1461, NA, 2615)
# Recalibrate the energy scale
C341 <- calibrate_energy(calib_spc[["C341"]], pks)
```

```{r plot-C341, echo=FALSE}
plot(C341, pks) +
  ggplot2::theme_bw()
```

#### C347
```{r calibrate-C347}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["C347"]] %>%
  slice_signal(-1:-40) %>%
  stabilize_signal(sqrt) %>%
  smooth_signal(method = "savitzky", m = 21) %>%
  remove_baseline() %>%
  find_peaks(span = 10)
# Set energy values
set_energy(pks) <- c(238, NA, NA, NA, NA, 1461, NA, 2615)
# Recalibrate the energy scale
C347 <- calibrate_energy(calib_spc[["C347"]], pks)
```

```{r plot-C347, echo=FALSE}
plot(C347, pks) +
  ggplot2::theme_bw()
```

#### GOU
```{r calibrate-GOU}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["GOU"]] %>%
  slice_signal(-1:-40) %>%
  stabilize_signal(sqrt) %>%
  smooth_signal(method = "savitzky", m = 21) %>%
  remove_baseline() %>%
  find_peaks()
# Set energy values
set_energy(pks) <- c(238, NA, NA, NA, 1461, NA, NA, 2615)
# Recalibrate the energy scale
GOU <- calibrate_energy(calib_spc[["GOU"]], pks)
```

```{r plot-GOU, echo=FALSE}
plot(GOU, pks) +
  ggplot2::theme_bw()
```

#### PEP
```{r calibrate-PEP}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["PEP"]] %>%
  slice_signal(-1:-40) %>%
  stabilize_signal(sqrt) %>%
  smooth_signal(method = "savitzky", m = 21) %>%
  remove_baseline() %>%
  find_peaks()
# Set energy values
set_energy(pks) <- c(238, NA, NA, NA, 1461, NA, NA, 2615)
# Recalibrate the energy scale
PEP <- calibrate_energy(calib_spc[["PEP"]], pks)
```

```{r plot-PEP, echo=FALSE}
plot(PEP, pks) +
  ggplot2::theme_bw()
```

### Background Noise Spectrum
```{r calibrate-noise}
# Pb212, K40, Tl208
lines <- list(
  chanel = c(86, 496, 870),
  energy = c(238, 1461, 2615)
)
noise_scaled <- calibrate_energy(noise_spc, lines = lines)
```

```{r plot-noise, echo=FALSE}
plot(noise_scaled, xaxis = "energy", yaxis = "rate") +
  ggplot2::geom_vline(xintercept = c(238, 1461, 2615), linetype = 3) +
  ggplot2::theme_bw()
```

## Signal Integration
```{r calib-scaled}
calib_scaled <- list(BRIQUE, C341, C347, GOU, PEP)
calib_scaled <- methods::as(calib_scaled, "GammaSpectra")
```

### Count Threshold
```{r integrate-Ni}
# Integration range (in keV)
Ni_integration_range <- c(200, 2800)

# Integrate background noise
Ni_background <- integrate_signal(
  noise_scaled,
  range = Ni_integration_range,
  threshold = "Ni"
)

# Integrate reference spectra
Ni_signal <- integrate_signal(
  calib_scaled, 
  range = Ni_integration_range, 
  background = Ni_background,
  threshold = "Ni",
  simplify = TRUE
)
```

```{r integrate-Ni-results, echo=FALSE}
knitr::kable(
  rbind(rbind(Ni_background), Ni_signal),
  digits = 3,
  caption = "Spectra integration - Ni"
)
```

### Energy Threshold
```{r integrate-NiEi}
# Integration range (in keV)
NiEi_integration_range <- c(200, 2800)

# Integrate background noise
NiEi_background <- integrate_signal(
  noise_scaled, 
  range = NiEi_integration_range,
  threshold = "NiEi"
)

# Integrate reference spectra
NiEi_signal <- integrate_signal(
  calib_scaled, 
  range = NiEi_integration_range, 
  background = NiEi_background,
  threshold = "NiEi",
  simplify = TRUE
)
```

```{r integrate-NiEi-results, echo=FALSE}
knitr::kable(
  rbind(rbind(NiEi_background), NiEi_signal),
  digits = 3,
  caption = "Spectra integration - NiEi"
)
```

## Calibration Curve
### Summary
```{r calibration, out.width='47%', fig.width=3.5, fig.height=3.5, fig.show='hold'}
data("AIX_NaI_curve")

# Plot calibration curve
plot(AIX_NaI_curve, threshold = "Ni") +
  ggplot2::theme_bw()
plot(AIX_NaI_curve, threshold = "NiEi") +
  ggplot2::theme_bw()
```

```{r calibration-data, echo=FALSE}
data("AIX_NaI_data")

# Display curve data
knitr::kable(AIX_NaI_data, row.names = FALSE)
```

```{r lm-summary_Ni, echo=FALSE}
summary(get_model(AIX_NaI_curve, "Ni"))
```

```{r lm-summary_NiEi, echo=FALSE}
summary(get_model(AIX_NaI_curve, "NiEi"))
```

### Check Model
#### Count Threshold (Ni)
```{r lm-check-Ni, echo=FALSE, out.width='47%', fig.width=3.5, fig.height=3.5, fig.show='hold'}
Ni_model <- get_model(AIX_NaI_curve, "Ni")
Ni_residuals <- data.frame(
  name = AIX_NaI_curve[["data"]]$name,
  fitted = Ni_model$fitted.values,
  residuals = Ni_model$residuals,
  standardized = stats::rstandard(Ni_model),
  cook = stats::cooks.distance(Ni_model)
)

# Residuals vs fitted values
ggplot2::ggplot(Ni_residuals, ggplot2::aes(x = fitted, y = residuals)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = residuals)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Residuals vs fitted values",
                x = "Fitted values", y = "Residuals")

# Std. residuals vs fitted values
ggplot2::ggplot(Ni_residuals, ggplot2::aes(x = fitted, y = standardized)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = c(-2, 2), linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = standardized)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Std. residuals vs fitted values",
                x = "Fitted values", y = "Standardized residuals")

# Normal QQ plot of standardized residuals
ggplot2::ggplot(Ni_residuals, ggplot2::aes(sample = standardized)) + 
  ggplot2::geom_abline(slope = 1, intercept = 0) +
  ggplot2::geom_qq_line(colour = "red") +
  ggplot2::geom_qq() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Normal QQ plot",
                x = "Theoretical quantiles",
                y = "Standardize residuals")

# Cook's distance
ggplot2::ggplot(Ni_residuals, ggplot2::aes(x = name, y = cook)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = 1, linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = name, xend = name,
                                     y = 0, yend = cook)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Cook's distance",
                x = "Observation", y = "D")
```

#### Energy Threshold (Ni.Ei)
```{r lm-check-NiEi, echo=FALSE, out.width='47%', fig.width=3.5, fig.height=3.5, fig.show='hold'}
NiEi_model <- get_model(AIX_NaI_curve, "NiEi")
NiEi_residuals <- data.frame(
  name = AIX_NaI_curve[["data"]]$name,
  fitted = NiEi_model$fitted.values,
  residuals = NiEi_model$residuals,
  standardized = stats::rstandard(NiEi_model),
  cook = stats::cooks.distance(NiEi_model)
)

# Residuals vs fitted values
ggplot2::ggplot(NiEi_residuals, ggplot2::aes(x = fitted, y = residuals)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = residuals)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Residuals vs fitted values",
                x = "Fitted values", y = "Residuals")

# Std. residuals vs fitted values
ggplot2::ggplot(NiEi_residuals, ggplot2::aes(x = fitted, y = standardized)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = c(-2, 2), linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = standardized)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Std. residuals vs fitted values",
                x = "Fitted values", y = "Standardized residuals")

# Normal QQ plot of standardized residuals
ggplot2::ggplot(NiEi_residuals, ggplot2::aes(sample = standardized)) + 
  ggplot2::geom_abline(slope = 1, intercept = 0) +
  ggplot2::geom_qq_line(colour = "red") +
  ggplot2::geom_qq() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Normal QQ plot",
                x = "Theoretical quantiles",
                y = "Standardize residuals")

# Cook's distance
ggplot2::ggplot(NiEi_residuals, ggplot2::aes(x = name, y = cook)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = 1, linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = name, xend = name,
                                     y = 0, yend = cook)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Cook's distance",
                x = "Observation", y = "D")
```

## R session
```{r session-info, echo=FALSE}
sessionInfo()
```
