---
title: "CEREGE Calibration Curve"
author: "N. Frerebeau, B. Lebrun"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amssymb}
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{cerege}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(gamma)
library(magrittr)
```

## Import files
```{r import, fig.width=7, fig.height=5, fig.align="center"}
# Import CNF files for calibration
cerege_cnf <- system.file("extdata/cerege/", package = "gamma")
cerege_spc <- read(cerege_cnf)
cerege_spc

# Select 'BRIQUE', 'C341', 'C347', 'GOU' and 'PEB' spectra to build the curve
cerege_calib <- cerege_spc[c("BRIQUE", "C341", "C347", "GOU", "PEP")]
# Select 'PB' spectra for background measurement
cerege_noise <- cerege_spc[["PB"]]

# Plot spectra
plot(cerege_calib) +
  ggplot2::geom_vline(xintercept = c(238, 1461, 2614.5), linetype = 3) +
  ggplot2::labs(x = "Energy [keV]", y = "Counts") +
  ggplot2::theme_bw()
```

## Check automatic peak detection
```{r peak}
# Remove base line
cerege_clean <- removeBaseline(cerege_calib)

# Fit peaks
cerege_fit <- lapply(X = cerege_clean, FUN = fitPeaks, peaks = c(238, 1461, 2614.5))
```

```{r peak-fit, fig.width=7, fig.height=5, fig.align="center", results="asis"}
# Visual inspection
expected_peaks <- c(238, 1461, 2614.5)

for (i in 1:length(cerege_fit)) {
  print(
    plot(cerege_fit[[i]]) +
      ggplot2::labs(title = cerege_fit[[i]][["spectrum"]][["reference"]], 
                    x = "Energy [keV]", y = "Counts") +
      ggplot2::theme_bw()
  )
  
  cerege_pks <- cerege_fit[[i]][["peaks"]] %>%
      dplyr::mutate(shift = (energy - expected_peaks) * 100 / 
                      abs(expected_peaks))
  
  print(
    knitr::kable(
      cerege_pks,
      digits = 3,
      col.names = c("Chanel", "Energy [keV]", "Count", 
                    "Count rate [1/s]", "Energy error [%]"),
      caption = cerege_fit[[i]][["spectrum"]][["reference"]]
    )
  )
  cat('\n')
}
```

## Check energy calibration
```{r adjust, fig.width=7, fig.height=5, fig.align="center"}
cerege_scale <- calibrateEnergy(cerege_calib, peaks = c(238, 1461, 2614.5))

plot(cerege_scale) +
  ggplot2::geom_vline(xintercept = c(238, 1461, 2614.5), linetype = 3) +
  ggplot2::labs(x = "Energy [keV]", y = "Count") +
  ggplot2::theme_bw()
```

## Background noise measurement
Pas fonctionnel du tout.
```{r background-noise, fig.width=7, fig.height=5, fig.align="center"}
# Plot spectrum
plot(cerege_noise) +
  ggplot2::labs(x = "Energy [keV]", y = "Counts") +
  ggplot2::theme_bw()
```

```{r peak-noise, eval=FALSE, include=FALSE, fig.width=7, fig.height=5, fig.align="center"}
# Remove base line
cerege_noise_clean <- removeBaseline(cerege_noise)
plot(noise_clean)

# Peak detection
noise_peak <- findPeaks(noise_clean, SNR = 1, span = 50)
plot(noise_peak)

knitr::kable(
  noise_peak[["peaks"]]
)

noise_fit <- fitPeaks(noise_clean, peaks = c(254.1352, 1488.6541, 2669.7403))
```

```{r integrate-noise, eval=FALSE, include=FALSE}
noise <- integrateSignal(cerege_noise)
```

## Build Calibration curve
```{r calibration, fig.width=5, fig.height=5, fig.align="center"}
# Build calibration curve
cerege_dose <- list(
  BRIQUE = c(1984.64, 34.08),
  C347 = c(1421.38, 25.25),
  C341 = c(849.01, 21.32),
  PEP = c(2535.53, 112.17),
  GOU = c(1573.41, 17.43)
)

CEREGE <- calibrateDose(
  cerege_scale,
  dose = cerege_dose,
  noise = list(value = 1190, error = 1)
)
CEREGE

# Plot Calibration curve
plot(CEREGE) +
  ggplot2::labs(x = "Signal", y = "Dose rate [µGy/y]") +
  ggplot2::theme_bw()
```

```{r save, eval=FALSE, echo=FALSE, include=FALSE}
usethis::use_data(CEREGE, overwrite = FALSE)
```
