---
title: "CRP2A Calibration Curve #1"
subtitle: "Canberra Inspector 1000 - LaBr"
author: "CRP2A Luminescence Team"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amssymb}
bibliography: bibliography.bib
vignette: >
  %\VignetteIndexEntry{CRP2A#1}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  comment = "#>"
)
library(gamma)
library(magrittr)
```

## Import files
```{r import}
# Import CNF files for calibration
# Skip the first chanels
calib_dir <- system.file("extdata/crp2a/calibration", package = "gamma")
(calib_spc <- read(calib_dir, skip = TRUE))

# Import CNF files for background noise measurement
# Skip the first chanels
noise_dir <- system.file("extdata/crp2a/background", package = "gamma")
(noise_spc <- read(noise_dir, skip = TRUE))
```

## Inspect spectra
```{r inspect, fig.width=7, fig.height=5, fig.align="center"}
# Plot calibration spectra
plot(calib_spc, xaxis = "energy", yaxis = "rate") +
  ggplot2::labs(title = "Reference spectra") +
  ggplot2::theme_bw()

# Plot background noise spectrum
plot(noise_spc) +
  ggplot2::labs(title = "Background noise spectrum") +
  ggplot2::theme_bw()
```

## Energy scale calibration
### Reference spectra
Energies in keV (expected chanel):

* Pb212: 238 (75)
* K40: 1461 (465)
* Tl208: 2615 (829)

#### BRIQUE
```{r calib-BRIQUE}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["BRIQUE"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, NA, NA, 1461, 2615)
# Recalibrate the energy scale
BRIQUE <- calibrate(calib_spc[["BRIQUE"]], pks)
```

#### C341
```{r calib-C341}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["C341"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, NA, NA, 1461, NA, NA, 2615)
# Recalibrate the energy scale
C341 <- calibrate(calib_spc[["C341"]], pks)
```

#### C347
```{r calib-C347}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["C347"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(SNR = 1, span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, NA, 1461, NA, NA, 2615)
# Recalibrate the energy scale
C347 <- calibrate(calib_spc[["C347"]], pks)
```

#### GOU
```{r calib-GOU}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["GOU"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, 1461, 2615)
# Recalibrate the energy scale
GOU <- calibrate(calib_spc[["GOU"]], pks)
```

#### LMP
```{r calib-LMP}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["LMP"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(SNR = 1, span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, 1461, NA, NA, NA, NA, 2615)
# Recalibrate the energy scale
LMP <- calibrate(calib_spc[["LMP"]], pks)
```

#### MAZ
```{r calib-MAZ}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["MAZ"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, NA, 1461, 2615)
# Recalibrate the energy scale
MAZ <- calibrate(calib_spc[["MAZ"]], pks)
```

#### PEP
```{r calib-PEP}
# Spectrum pre-processing and peak detection
pks <- calib_spc[["PEP"]] %>%
  smooth(method = "savitzky", m = 21) %>%
  removeBaseline(decreasing = TRUE, k = 100) %>%
  findPeaks(span = 20)
# Set energy values
setEnergy(pks) <- c(NA, 238, NA, NA, NA, NA, NA, NA, 1461, 2615)
# Recalibrate the energy scale
PEP <- calibrate(calib_spc[["PEP"]], pks)
```

#### Inspect results
```{r calib-scale, fig.width=7, fig.height=5, fig.align="center"}
# Energy scale calibration
calib_scaled <- list(BRIQUE, C341, C347, GOU, LMP, MAZ, PEP)
calib_scaled <- methods::as(calib_scaled, "GammaSpectra")

plot(calib_scaled, xaxis = "energy", yaxis = "rate") +
  ggplot2::labs(title = "Calibrated spectra") +
  ggplot2::theme_bw()
```

### Background noise spectrum
```{r calibrate-noise, fig.width=7, fig.height=5, fig.align="center"}
noise_lines <- list(
  La138 = c(chanel = 251, energy = 789),
  K40 = c(chanel = 460, energy = 1461),
  Tl208 = c(chanel = 814, energy = 2615)
)
noise_scaled <- calibrate(noise_spc, lines = noise_lines)

plot(noise_spc, noise_scaled, xaxis = "energy", yaxis = "rate") +
  ggplot2::geom_vline(xintercept = c(789, 1461, 2615), linetype = 3) +
  ggplot2::theme_bw()
```

## Signal integration
### Get integration boudaries
```{r integrate-bounds}
# Integration range (in keV)
integration_range <- c(165, 2800)
```

### Integrate
```{r integrate-norm}
# Integrate background noise
# Compare with previous value of 25279.63 +/- 1.66
noise <- integrateSignal(
  noise_scaled,
  range = integration_range,
  NiEi = TRUE
)
knitr::kable(
  rbind(noise),
  digits = 3,
  caption = "Background spectrum integration"
)

# Integrate reference spectra
signal <- integrateSignal(
  calib_scaled, 
  range = integration_range, 
  noise = noise,
  NiEi = TRUE,
  simplify = TRUE
)
knitr::kable(
  signal,
  digits = 3,
  caption = "Reference spectra integration"
)
```

## Build Calibration curve
### Set dose rates
```{r dose_rate}
setDoseRate(calib_scaled) <- list(
  BRIQUE = c(1986, 36),
  C341 = c(850, 21),
  C347 = c(1424, 24),
  GOU = c(1575, 17),
  LMP = c(642, 18),
  MAZ = c(1141, 12),
  PEP = c(2538, 112)
)

getDoseRate(calib_scaled)
```

### Linear regression
```{r calibration, fig.width=5, fig.height=5, fig.align="center"}
# Build calibration curve
(BDX1 <- fit(
  calib_scaled,
  noise_scaled,
  range = integration_range,
  intercept = TRUE,
  details = list(
    laboratory = "IRAMAT-CRP2A (UMR 5060)",
    instrument = "InSpector 1000",
    detector = "LaBr",
    authors = "CRP2A Luminescence Team"
  )
))

# Plot Calibration curve
plot(BDX1) +
  ggplot2::theme_bw()
```

```{r save, eval=FALSE, echo=FALSE, include=FALSE}
# Danger zone ! Don't touch !
usethis::use_data(BDX1, overwrite = FALSE)
```

### Check model
```{r lm-summary, echo=FALSE}
summary(BDX1[["model"]])
```

```{r lm-check, echo=FALSE, warning=FALSE, fig.width=7, fig.height=7, fig.align="center"}
calib_residuals <- data.frame(
  reference = BDX1[["data"]]$reference,
  fitted = BDX1[["model"]]$fitted.values,
  residuals = BDX1[["model"]]$residuals,
  standardized = stats::rstandard(BDX1[["model"]]),
  cook = stats::cooks.distance(BDX1[["model"]])
)

# Residuals vs fitted values
plot_res <- ggplot2::ggplot(calib_residuals, 
                            ggplot2::aes(x = fitted, y = residuals)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = residuals)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Residuals vs fitted values",
                x = "Fitted values", y = "Residuals")

# Std. residuals vs fitted values
plot_stdres <- ggplot2::ggplot(calib_residuals, 
                               ggplot2::aes(x = fitted, y = standardized)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = c(-2, 2), linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = fitted, xend = fitted,
                                     y = 0, yend = standardized)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Std. residuals vs fitted values",
                x = "Fitted values", y = "Standardized residuals")

# Normal QQ plot of standardized residuals
plot_qq <- ggplot2::ggplot(calib_residuals, 
                           ggplot2::aes(sample = standardized)) + 
  ggplot2::geom_abline(slope = 1, intercept = 0) +
  ggplot2::geom_qq_line(colour = "red") +
  ggplot2::geom_qq() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Normal QQ plot",
                x = "Theoretical quantiles",
                y = "Standardize residuals")

# Cook's distance
plot_cook <- ggplot2::ggplot(calib_residuals, 
                             ggplot2::aes(x = reference, y = cook)) +
  ggplot2::geom_hline(yintercept = 0, linetype = 3) +
  ggplot2::geom_hline(yintercept = 1, linetype = 2) +
  ggplot2::geom_segment(ggplot2::aes(x = reference, xend = reference,
                                     y = 0, yend = cook)) + 
  ggplot2::geom_point() +
  ggplot2::theme_bw() +
  ggplot2::labs(title = "Cook's distance",
                x = "Observation", y = "D")

# Relative error on dose rate estimation
dose_predict <- predict(BDX1, epsilon = 0.03, simplify = TRUE) %>%
  as.data.frame() %>%
  dplyr::transmute(reference = rownames(.),
                   pred_value = value, 
                   pred_error = error)

dose_known <- getDoseRate(calib_scaled) %>%
  as.data.frame() %>%
  dplyr::transmute(reference = rownames(.),
                   exp_value = value, 
                   exp_error = error)

dose_errors <- merge(dose_predict, dose_known, by = "reference") %>%
  dplyr::mutate(rel_error = ((pred_value - exp_value) / exp_value) * 100)

plot_errors <- ggplot2::ggplot(dose_errors, 
                               ggplot2::aes(x = reference, y = rel_error)) +
  ggplot2::geom_col() +
  ggplot2::labs(title = "Relative error on fitted values",
                x = "Reference", y = "Relative error [%]") +
  ggplot2::theme_bw()

cowplot::plot_grid(
  plot_res, plot_stdres, plot_cook, plot_qq,
  ncol = 2, labels = "AUTO"
)
```

## Compare with previous values
```{r test-import}
# Import CNF files for calibration
# Skip the 30 first chanels
test_dir <- system.file("extdata/crp2a/test", package = "gamma")
(test_spc <- read(test_dir, skip = TRUE))
```

```{r test-calibrate, fig.width=7, fig.height=5, fig.align="center"}
# Peak parameters estimation
# Fit peaks at chanel 75, 463, 825 (starting positions)
# (expected energy: 238, 1461, 2615 keV)
test_peaks <- lapply(
  X = test_spc, 
  FUN = fitPeaks, 
  peaks = c(75, 463, 825),
  bounds = c(0.5)
)
# Expected energies (keV)
expected_peaks <- c(Pb212 = 238, K40 = 1461, Tl208 = 2615)

# Energy scale calibration
test_scaled <- lapply(X = test_peaks, FUN = calibrate,  lines = expected_peaks)
test_scaled <- methods::as(test_scaled, "GammaSpectra")

plot(test_scaled, xaxis = "energy", yaxis = "rate") +
  ggplot2::geom_vline(xintercept = expected_peaks, linetype = 3) +
  ggplot2::theme_bw()
```

```{r test-dose, fig.width=7, fig.height=5, fig.align="center"}
# Estimate the gamma dose rate
test_dose <- predict(BDX1, test_scaled, simplify = TRUE)
```

```{r test-dose-table, echo=FALSE}
knitr::kable(
  test_dose,
  digits = 3,
  col.names = c("Dose", "Dose error"),
  caption = "Gamma dose rate estimates"
)
```

```{r integrate-diff, echo=FALSE, fig.width=5, fig.height=3.5, fig.align="center"}
# Results from the VBA macro in use in the laboratory
test_diff <- test_dose %>%
  as.data.frame() %>%
  dplyr::mutate(
  #   signal_old = c(13491.21, 9482.82, 9398.50, 7695.64, 48385.39, 15836.60,
  #                  14668.34, 14446.89, 12078.79, 10786.86),
    reference = rownames(.),
    dose_old = c(405, 279, 276, 223, 1500, 478, 442, 435, 360, 320)) %>%
  dplyr::mutate(dose_diff = ((value - dose_old) / dose_old) * 100)

# plot_signal <- ggplot2::ggplot(
#   data = test_diff,
#   mapping = ggplot2::aes(x = reference, y = signal_diff)) +
#   ggplot2::geom_col() +
#   ggplot2::labs(title = "Spectrum integration",
#                 x = "Reference", y = "Relative difference [%]") +
#   ggplot2::theme_bw() +
#   ggplot2::theme(axis.text.x = ggplot2::element_text(vjust = 0.5, angle = 90))

plot_dose <- ggplot2::ggplot(
  data = test_diff,
  mapping = ggplot2::aes(x = reference, y = dose_diff)) +
  ggplot2::geom_col() +
  ggplot2::labs(title = "Gamma dose rate",
                x = "Reference", y = "Relative difference [%]") +
  ggplot2::theme_bw() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(vjust = 0.5, angle = 90))
plot_dose

# cowplot::plot_grid(
#   plot_signal, plot_dose,
#   ncol = 2, labels = "AUTO"
# )
```

## R session
```{r session-info, echo=FALSE}
sessionInfo()
```
